import { TeeError } from '../common/tee-error';

/** Account IDs are generated by core; a collision suffix can make them 64 characters. */
const ACCOUNT_SLUG_RE = /^[a-z0-9][a-z0-9-]{0,63}$/;

export function assertValidAccountSlug(slug: unknown): string {
  if (typeof slug !== 'string' || !ACCOUNT_SLUG_RE.test(slug)) {
    throw new TeeError('TEE_INVALID_SLUG', 'account slug must be a lowercase slug', {
      expected: 'lowercase letters, digits and hyphens; must start alphanumeric; max 64 chars',
    });
  }
  return slug;
}
